<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;

class SendEmailController extends Controller
{
    function send(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'rg' => 'nullable',
            'orgao' => 'nullable',
            'data_emissao' => 'nullable',
            'uf_emissao' => 'nullable',
            'cpf' => 'nullable',
            'sexo' => 'nullable',
            'naturalidade' => 'nullable',
            'nacionalidade' => 'nullable',
            'endereco' => 'nullable',
            'numero' => 'nullable',
            'bairro' => 'nullable',
            'complemento' => 'nullable',
            'cidade' => 'nullable',
            'uf' => 'nullable',
            'pais' => 'nullable',
            'telefone' => 'nullable',
            'telefone_celular' => 'nullable',
            'telefone_trabalho' => 'nullable',
            'curso' => 'nullable',
            'categoria_ies' => 'nullable',
            'nome_ies' => 'nullable',
            'sigla_ies' => 'nullable',
            'pais_graduacao' => 'nullable',
            'ano_titulacao' => 'nullable',
            'uf_graduacao' => 'nullable',
            'possui_curso_graduacao' => 'nullable',
            'outro_curso_pos_graduacao' => 'nullable',
            'curso_mestrado' => 'nullable',
            'nome_da_ies_mestrado' => 'nullable',
            'categoria_da_ies_mestrado' => 'nullable',
            'sigla_da_ies_mestrado' => 'nullable',
            'ano_titulacao_mestrado' => 'nullable',
            'uf_mestrado' => 'nullable',
            'pais_mestrado' => 'nullable',
            'candidato_sistema_cotas' => 'nullable',
            'trabalhando' => 'nullable',
            'insercao_trabalho' => 'nullable',
            'experiencia_docente' => 'nullable',
            'experiencia_supervisor' => 'nullable',
            'interesse_bolsa' => 'nullable',
            'natureza_instituicao' => 'nullable',
            'idiomas' => 'nullable',
            'certificado_lingua_estrangeira' => 'nullable',
            'solicita_isencao' => 'nullable',
            'justifica_isenscao' => 'nullable',
            'aspectos_interesse' => 'nullable',
            'linha_pesquisa' => 'nullable',
            'titulo_resumo_projeto' => 'nullable',
            'titulo' => 'nullable',
            'email' => 'nullable'
        ]);
        $data = array(
            'name' => $request->name,
            'rg' => $request->rg,
            'orgao' => $request->orgao,
            'data_emissao' => $request->data_emissao,
            'uf_emissao' => $request->uf_emissao,
            'cpf' => $request->cpf,
            'sexo' => $request->sexo,
            'naturalidade' => $request->naturalidade,
            'nacionalidade' => $request->nacionalidade,
            'endereco' => $request->endereco,
            'numero' => $request->numero,
            'bairro' => $request->bairro,
            'complemento' => $request->complemento,
            'cidade' => $request->cidade,
            'uf' => $request->uf,
            'pais' => $request->pais,
            'telefone' => $request->telefone,
            'telefone_celular' => $request->telefone_celular,
            'telefone_trabalho' => $request->telefone_trabalho,
            'curso' => $request->curso,
            'categoria_ies' => $request->categoria_ies,
            'nome_ies' => $request->nome_ies,
            'sigla_ies' => $request->sigla_ies,
            'pais_graduacao' => $request->pais_graduacao,
            'ano_titulacao' => $request->ano_titulacao,
            'uf_graduacao' => $request->uf_graduacao,
            'possui_curso_graduacao' => $request->possui_curso_graduacao,
            'outro_curso_pos_graduacao' => $request->outro_curso_pos_graduacao,
            'curso_mestrado' => $request->curso_mestrado,
            'nome_da_ies_mestrado' => $request->nome_da_ies_mestrado,
            'categoria_da_ies_mestrado' => $request->categoria_da_ies_mestrado,
            'sigla_da_ies_mestrado' => $request->sigla_da_ies_mestrado,
            'ano_titulacao_mestrado' => $request->ano_titulacao_mestrado,
            'uf_mestrado' => $request->uf_mestrado,
            'pais_mestrado' => $request->pais_mestrado,
            'candidato_sistema_cotas' => $request->candidato_sistema_cotas,
            'trabalhando' => $request->trabalhando,
            'insercao_trabalho' => $request->insercao_trabalho,
            'experiencia_docente' => $request->experiencia_docente,
            'experiencia_supervisor' => $request->experiencia_supervisor,
            'interesse_bolsa' => $request->interesse_bolsa,
            'natureza_instituicao' => $request->natureza_instituicao,
            'idiomas' => $request->idiomas,
            'certificado_lingua_estrangeira' => $request->certificado_lingua_estrangeira,
            'solicita_isencao' => $request->solicita_isencao,
            'justifica_isencao' => $request->justifica_isencao,
            'aspectos_interesse' => $request->aspectos_interesse,
            'linha_pesquisa' => $request->linha_pesquisa,
            'titulo_resumo_projeto' => $request->titulo_resumo_projeto,
            'titulo' => $request->titulo,
            'email' => $request->email
        );

        Mail::to('juniozguedes@gmail.com')->send( new SendMail($data)); //E-mail que vai RECEBER a mensagem na inbox
        return back()->with('sucess', 'Obrigado pelo contato!');
    }
}
